name: Static Website Hosting To S3 Bucket

on: [push]
jobs:
        deploy-to-s3:
            runs-on: ubuntu-latest
            steps:
               -  name: Checkout Repositry Code
                  uses: actions/checkout@v3

               - name: Aws Credentials
                 uses: aws-actions/configure-aws-credentials@v2
                 with:
                   aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                   aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                   aws-region: us-southeast-2

               - name: Push to s3 bucket
                 run: aws s3 sync . s3://my-aws-bucket-for-websitedev
